authors:
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/932156
  senthilsweb:
    name: Senthilnathan Karuppaiah
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/1448503
